theme: jekyll-theme-tactile
google_analytics: UA-114571919-1
current-contribution-url: "https://github.com/modelica/newsletter/tree/master/_2018-01"
contribution-open: true
contribution-deadline: 23 March
current-newsletter-date: 02 April
baseurl: /newsletter
url: "https://modelica.github.io"
collections:
  2015-03:
    permalink: /:collection/:path
    title: Old newsletter
    date: 2015-11-04
    output: true
  2018-01:
    permalink: /:collection/:path
    title: First release!
    date: 2018-04-02
    output: true
